/// <reference path= '../enum/SlotEnum.ts'/>
/// <reference path= '../enum/DataEnum.ts'/>
namespace Dev.Config {

    export class DataConfig {

        static PayoutData : Array<Interface.IPayout> = [
            {
                combination:[
                    {count:3,symbol:Enum.SlotSymbol.CherrySymbol}
                ],
                payout:{coins:2000,cents:2000},
                lineIndex:Enum.LineType.top
            },
            {
                combination:[
                    {count:3,symbol:Enum.SlotSymbol.SevenSymbol}
                ],
                payout:{coins:150,cents:150},
                lineIndex:Enum.LineType.top
            }, 
            {
                combination:[
                    {count:3,symbol:Enum.SlotSymbol.BarSymbol}
                ],
                payout:{coins:10,cents:10},
                lineIndex:Enum.LineType.top
            },
            {
                combination:[
                    {count:3,symbol:Enum.SlotSymbol.Bar3xSymbol}
                ],
                payout:{coins:50,cents:50},
                lineIndex:Enum.LineType.top
            },
            {
                combination:[
                    {count:1,symbol:Enum.SlotSymbol.SevenSymbol},
                    {count:1,symbol:Enum.SlotSymbol.CherrySymbol}
                ],
                payout:{coins:75,cents:75},
                lineIndex:Enum.LineType.top
            },
            {
                combination:[
                    {count:3,symbol:Enum.SlotSymbol.Bar2xSymbol}
                ],
                payout:{coins:20,cents:20},
                lineIndex:Enum.LineType.top
            },
            {
                combination:[
                    {count:1,symbol:Enum.SlotSymbol.BarSymbol}
                ],
                payout:{coins:5,cents:5},
                lineIndex:Enum.LineType.top
            },
            {
                combination:[
                    {count:3,symbol:Enum.SlotSymbol.CherrySymbol}
                ],
                payout:{coins:1000,cents:1000},
                lineIndex:Enum.LineType.center
            },
            {
                combination:[
                    {count:3,symbol:Enum.SlotSymbol.SevenSymbol}
                ],
                payout:{coins:150,cents:150},
                lineIndex:Enum.LineType.center
            },    {
                combination:[
                    {count:3,symbol:Enum.SlotSymbol.Bar3xSymbol}
                ],
                payout:{coins:50,cents:50},
                lineIndex:Enum.LineType.center
            },{
                combination:[
                    {count:3,symbol:Enum.SlotSymbol.Bar2xSymbol}
                ],
                payout:{coins:20,cents:20},
                lineIndex:Enum.LineType.center
            }, {
                combination:[
                    {count:3,symbol:Enum.SlotSymbol.BarSymbol}
                ],
                payout:{coins:10,cents:10},
                lineIndex:Enum.LineType.center
            },
            {
                combination:[
                    {count:1,symbol:Enum.SlotSymbol.BarSymbol}
                ],
                payout:{coins:5,cents:5},
                lineIndex:Enum.LineType.center
            },
            {
                combination:[
                    {count:3,symbol:Enum.SlotSymbol.CherrySymbol}
                ],
                payout:{coins:4000,cents:4000},
                lineIndex:Enum.LineType.bottom
            },
            {
                combination:[
                    {count:3,symbol:Enum.SlotSymbol.SevenSymbol}
                ],
                payout:{coins:150,cents:150},
                lineIndex:Enum.LineType.bottom
            },
            {
                combination:[
                    {count:1,symbol:Enum.SlotSymbol.CherrySymbol},
                    {count:1,symbol:Enum.SlotSymbol.SevenSymbol}
                ],
                payout:{coins:75,cents:75},
                lineIndex:Enum.LineType.center
            },
            {
                combination:[
                    {count:1,symbol:Enum.SlotSymbol.CherrySymbol},
                    {count:1,symbol:Enum.SlotSymbol.SevenSymbol}
                ],
                payout:{coins:75,cents:75},
                lineIndex:Enum.LineType.bottom
            },
            {
                combination:[
                    {count:3,symbol:Enum.SlotSymbol.Bar3xSymbol}
                ],
                payout:{coins:50,cents:50},
                lineIndex:Enum.LineType.bottom
            },
            
            {
                combination:[
                    {count:3,symbol:Enum.SlotSymbol.Bar2xSymbol}
                ],
                payout:{coins:20,cents:20},
                lineIndex:Enum.LineType.bottom
            },
           
            {
                combination:[
                    {count:3,symbol:Enum.SlotSymbol.BarSymbol}
                ],
                payout:{coins:10,cents:10},
                lineIndex:Enum.LineType.bottom
            },
            {
                combination:[
                    {count:1,symbol:Enum.SlotSymbol.BarSymbol}
                ],
                payout:{coins:5,cents:5},
                lineIndex:Enum.LineType.bottom
            }
        ]
    }
}